### ISSUE TITLE
Building is failing due to new paths for bounding_region and overlapping_type

### ISSUE THREAD

**Issue by kmilo7204** [maliput/maliput_object_py#7]
## Environment
* OS Version: 
Ubuntu 20.04 
* Source build: 
  * Branch: main
  * Latest commit: b8d540f4fa6f5854e95c273a50893e1bcbb028f3

## Description
* Expected behavior:
 Workspace building must be successful when running `colcon build`.
* Actual behavior: 
Building is failing due to https://github.com/maliput/maliput_object/pull/44, The error is caused because bounding_region and overlapping_type were moved from `maliput_object::api` to `maliput::math`. Include headers and objects namespaces were not updated.  

## Steps to reproduce
Follow [Source installation on Ubuntu](https://github.com/maliput/maliput#source-installation-on-ubuntu) to reproduce the issue.

**Comment by francocipollone** [comment]
Hey @kmilo7204 , thanks for filling the issue.

1 . From what you mentioned you are building `maliput_object`, but are you also building their dependencies or you are relying on debians (talking about `maliput` package in particular)? 

2. Can you post the error mentioning the missing headers?

I just tried building up to `maliput_object`(including `maliput` package) and I had no troubles so I guess you installed `maliput` package via debians. Is that correct?

**Comment by francocipollone** [comment]
> Hey @kmilo7204 , thanks for filling the issue.
> 
> 1 . From what you mentioned you are building `maliput_object`, but are you also building their dependencies or you are relying on debians (talking about `maliput` package in particular)?
> 
> 2. Can you post the error mentioning the missing headers?
> 
> I just tried building up to `maliput_object`(including `maliput` package) and I had no troubles so I guess you installed `maliput` package via debians. Is that correct?

Nevermind I was checking `maliput_object`, you were right @kmilo7204 

Thanks, the fix is at #8

**Comment by francocipollone** [comment]
@kmilo7204 Fixed!
